// Module Boundary: core/
// Markdown report generator — produces a human-readable summary of the
// current verification state (trace stats, roofline classification,
// synth utilisation + timing) as a single Markdown string.
//
// Consumers (the UI's Report tab, CI logs, PR description snippets, …)
// just need to string-concat the output; no heavy templating engine.

use crate::hw_model::HardwareModel;
use crate::roofline::{analyze, RooflinePoint};
use crate::synth_report::SynthReport;
use crate::trace::NpuTrace;

/// Build a Markdown report that snapshots the state of a pccx-FPGA
/// verification run. Any section whose input is `None` is silently
/// omitted so callers can pick and choose what to render.
pub fn render_markdown(
    trace: Option<&NpuTrace>,
    synth: Option<&SynthReport>,
) -> String {
    let mut out = String::new();
    out.push_str("# pccx verification report\n\n");

    if trace.is_none() && synth.is_none() {
        out.push_str("_No trace and no synth report available to summarise._\n");
        return out;
    }

    if let Some(tr) = trace {
        render_trace_section(tr, &mut out);
        render_roofline_section(tr, &mut out);
    }

    if let Some(sr) = synth {
        render_synth_section(sr, &mut out);
    }

    out.push_str("\n---\n");
    out.push_str("_Generated by pccx-core ");
    out.push_str(env!("CARGO_PKG_VERSION"));
    out.push_str(" · pccx-lab markdown report generator._\n");
    out
}

fn render_trace_section(trace: &NpuTrace, out: &mut String) {
    out.push_str("## Trace summary\n\n");
    out.push_str(&format!("- **Total cycles:** {}\n", trace.total_cycles));
    out.push_str(&format!("- **Events:** {}\n", trace.events.len()));

    // Per-type histogram.
    let mut counts: std::collections::BTreeMap<&str, u64> =
        std::collections::BTreeMap::new();
    for ev in &trace.events {
        *counts.entry(ev.event_type.as_str()).or_insert(0) += 1;
    }
    if !counts.is_empty() {
        out.push_str("\n| Event type | Count |\n|---|---:|\n");
        for (ty, n) in &counts {
            out.push_str(&format!("| `{ty}` | {n} |\n"));
        }
    }

    // Core utilisation (quick peek, top 8 cores).
    let utils = trace.core_utilisation();
    if !utils.is_empty() {
        out.push_str("\n### Core utilisation (top 8)\n\n");
        out.push_str("| Core | Util % |\n|---:|---:|\n");
        for (core, pct) in utils.iter().take(8) {
            out.push_str(&format!("| {core} | {:.1} |\n", pct * 100.0));
        }
    }
    out.push('\n');
}

fn render_roofline_section(trace: &NpuTrace, out: &mut String) {
    let hw = HardwareModel::pccx_reference();
    let point: RooflinePoint = analyze(trace, &hw);

    out.push_str("## Roofline\n\n");
    out.push_str(&format!(
        "- **Arithmetic intensity:** {:.2} ops/byte\n",
        point.arithmetic_intensity
    ));
    out.push_str(&format!(
        "- **Achieved:** {:.2} GOPS (peak {:.0} GOPS compute, {:.1} GB/s memory)\n",
        point.achieved_gops, point.peak_gops, point.peak_bw_gbps
    ));
    let verdict = if point.compute_bound {
        "✅ compute-bound"
    } else {
        "⚠️ memory-bound"
    };
    out.push_str(&format!("- **Verdict:** {verdict}\n\n"));
}

fn render_synth_section(synth: &SynthReport, out: &mut String) {
    out.push_str("## Synthesis status\n\n");
    out.push_str(&format!(
        "- **Top module:** `{}`  \n  **Device:** `{}`\n",
        synth.utilisation.top_module, synth.device
    ));
    out.push_str("\n| Resource | Count |\n|---|---:|\n");
    out.push_str(&format!("| LUT    | {} |\n", synth.utilisation.total_luts));
    out.push_str(&format!("| Logic LUT | {} |\n", synth.utilisation.logic_luts));
    out.push_str(&format!("| FF     | {} |\n", synth.utilisation.ffs));
    out.push_str(&format!("| RAMB36 | {} |\n", synth.utilisation.rams_36));
    out.push_str(&format!("| RAMB18 | {} |\n", synth.utilisation.rams_18));
    out.push_str(&format!("| URAM   | {} |\n", synth.utilisation.urams));
    out.push_str(&format!("| DSP    | {} |\n", synth.utilisation.dsps));

    out.push_str("\n### Timing\n\n");
    let verdict = if synth.timing.is_timing_met {
        "✅ Timing met"
    } else {
        "❌ Timing NOT met"
    };
    out.push_str(&format!("- {verdict}\n"));
    out.push_str(&format!(
        "- **WNS:** {:.3} ns on `{}`\n",
        synth.timing.wns_ns,
        if synth.timing.worst_clock.is_empty() {
            "—"
        } else {
            &synth.timing.worst_clock
        }
    ));
    out.push_str(&format!(
        "- **Endpoints:** {} failing / {} total\n",
        synth.timing.failing_endpoints, synth.timing.total_endpoints
    ));
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::synth_report::{TimingSummary, UtilSummary};
    use crate::trace::NpuEvent;

    #[test]
    fn test_render_empty_is_graceful() {
        let md = render_markdown(None, None);
        assert!(md.contains("# pccx verification report"));
        assert!(md.contains("No trace and no synth report"));
    }

    #[test]
    fn test_render_trace_only() {
        let trace = NpuTrace {
            total_cycles: 100,
            events: vec![
                NpuEvent { core_id: 0, start_cycle: 0,  duration: 50, event_type: "MAC_COMPUTE".into() },
                NpuEvent { core_id: 1, start_cycle: 50, duration: 50, event_type: "DMA_READ".into() },
            ],
        };
        let md = render_markdown(Some(&trace), None);
        assert!(md.contains("## Trace summary"));
        assert!(md.contains("Total cycles:** 100"));
        assert!(md.contains("`MAC_COMPUTE`"));
        assert!(md.contains("## Roofline"));
        assert!(!md.contains("## Synthesis status"),
            "should not emit synth when input was None");
    }

    #[test]
    fn test_render_synth_with_failure_flagged() {
        let synth = SynthReport {
            utilisation: UtilSummary {
                top_module: "NPU_top".into(),
                total_luts: 5611,
                logic_luts: 5570,
                ffs: 8458,
                rams_36: 80,
                rams_18: 8,
                urams:   56,
                dsps:     4,
            },
            timing: TimingSummary {
                wns_ns: -9.792,
                tns_ns: -3615.208,
                failing_endpoints: 4194,
                total_endpoints:   28602,
                is_timing_met:     false,
                worst_clock:       "core_clk".into(),
            },
            device: "xck26-sfvc784-2LV-c".into(),
        };
        let md = render_markdown(None, Some(&synth));
        assert!(md.contains("NPU_top"));
        assert!(md.contains("xck26-sfvc784"));
        assert!(md.contains("| DSP    | 4 |"));
        assert!(md.contains("❌ Timing NOT met"));
        assert!(md.contains("-9.792"));
        assert!(md.contains("core_clk"));
    }
}
